//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.IranKish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IKCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IKCResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlinePayment.IranKish.IKCResource", typeof(IKCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات پرداخت با موفقیت صورت پذیرفت و تایید نهایی آن نیز اخذ گردید..
        /// </summary>
        internal static string _10000 {
            get {
                return ResourceManager.GetString("_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وجود کاراکترهای غیر مجاز در درخواست.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش قبلا برگشت خورده است.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای برقراری ارتباط با بانک مقصد.
        /// </summary>
        internal static string _30000 {
            get {
                return ResourceManager.GetString("_30000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول رشته درخواست غیر مجاز است.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در درخواست.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش مورد نظر یافت نشد.
        /// </summary>
        internal static string _80 {
            get {
                return ResourceManager.GetString("_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای داخلی بانک.
        /// </summary>
        internal static string _81 {
            get {
                return ResourceManager.GetString("_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش قبلا تایید شده است.
        /// </summary>
        internal static string _90 {
            get {
                return ResourceManager.GetString("_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش با موفقیت انجام گرفت..
        /// </summary>
        internal static string plus100 {
            get {
                return ResourceManager.GetString("plus100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف از ادامه پرداخت..
        /// </summary>
        internal static string plus110 {
            get {
                return ResourceManager.GetString("plus110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی حساب کافی نیست.
        /// </summary>
        internal static string plus120 {
            get {
                return ResourceManager.GetString("plus120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کارت اشتباه است.
        /// </summary>
        internal static string plus130 {
            get {
                return ResourceManager.GetString("plus130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز کارت اشتباه است.
        /// </summary>
        internal static string plus131 {
            get {
                return ResourceManager.GetString("plus131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت مسدود شده است.
        /// </summary>
        internal static string plus132 {
            get {
                return ResourceManager.GetString("plus132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت منقضی شده است.
        /// </summary>
        internal static string plus133 {
            get {
                return ResourceManager.GetString("plus133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان مورد نظر به پایان رسیده است.
        /// </summary>
        internal static string plus140 {
            get {
                return ResourceManager.GetString("plus140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای داخلی بانک.
        /// </summary>
        internal static string plus150 {
            get {
                return ResourceManager.GetString("plus150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اطلاعات تاریخ پایان اعتبار کارت و یا cvv2.
        /// </summary>
        internal static string plus160 {
            get {
                return ResourceManager.GetString("plus160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک صادر کننده کارت شما مجوز انجام تراکنش را صادر نکرده است..
        /// </summary>
        internal static string plus166 {
            get {
                return ResourceManager.GetString("plus166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش بیشتر از سقف مجاز برای هر تراکنش می باشد..
        /// </summary>
        internal static string plus200 {
            get {
                return ResourceManager.GetString("plus200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش بیشتر از سقف مجاز در روز می باشد..
        /// </summary>
        internal static string plus201 {
            get {
                return ResourceManager.GetString("plus201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش بیشتر از سقف مجاز در ماه می باشد..
        /// </summary>
        internal static string plus202 {
            get {
                return ResourceManager.GetString("plus202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سیستمی رخ داده، لطفا مجدد تلاس فرمایید..
        /// </summary>
        internal static string plus8 {
            get {
                return ResourceManager.GetString("plus8", resourceCulture);
            }
        }
    }
}
