//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.MabnaCardVerifyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.s2m.messaging/", ConfigurationName="MabnaCardVerifyService.TransactionReference")]
    public interface TransactionReference {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.s2m.messaging/TransactionReference/sendConfirmationRequest", ReplyAction="http://ws.s2m.messaging/TransactionReference/sendConfirmationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseMessageSpec))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestMessageSpec))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OnlinePayment.MabnaCardVerifyService.sendConfirmationResponse sendConfirmation(OnlinePayment.MabnaCardVerifyService.sendConfirmationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.s2m.messaging/TransactionReference/sendConfirmationRequest", ReplyAction="http://ws.s2m.messaging/TransactionReference/sendConfirmationResponse")]
        System.Threading.Tasks.Task<OnlinePayment.MabnaCardVerifyService.sendConfirmationResponse> sendConfirmationAsync(OnlinePayment.MabnaCardVerifyService.sendConfirmationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.s2m.messaging/")]
    public partial class confirmationDTO : requestMessageSpec {
        
        private string cRNField;
        
        private string mIDField;
        
        private string sIGNATUREField;
        
        private string tRNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CRN {
            get {
                return this.cRNField;
            }
            set {
                this.cRNField = value;
                this.RaisePropertyChanged("CRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MID {
            get {
                return this.mIDField;
            }
            set {
                this.mIDField = value;
                this.RaisePropertyChanged("MID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SIGNATURE {
            get {
                return this.sIGNATUREField;
            }
            set {
                this.sIGNATUREField = value;
                this.RaisePropertyChanged("SIGNATURE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRN {
            get {
                return this.tRNField;
            }
            set {
                this.tRNField = value;
                this.RaisePropertyChanged("TRN");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(confirmationDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.s2m.messaging/")]
    public abstract partial class requestMessageSpec : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(generalResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saleConfResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.s2m.messaging/")]
    public abstract partial class responseMessageSpec : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
                this.RaisePropertyChanged("successful");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saleConfResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.s2m.messaging/")]
    public partial class generalResponse : responseMessageSpec {
        
        private string aIRField;
        
        private string dATEField;
        
        private string rESCODEField;
        
        private string sIGNATUREField;
        
        private string sTANField;
        
        private string tIMEField;
        
        private string tRNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AIR {
            get {
                return this.aIRField;
            }
            set {
                this.aIRField = value;
                this.RaisePropertyChanged("AIR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DATE {
            get {
                return this.dATEField;
            }
            set {
                this.dATEField = value;
                this.RaisePropertyChanged("DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RESCODE {
            get {
                return this.rESCODEField;
            }
            set {
                this.rESCODEField = value;
                this.RaisePropertyChanged("RESCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SIGNATURE {
            get {
                return this.sIGNATUREField;
            }
            set {
                this.sIGNATUREField = value;
                this.RaisePropertyChanged("SIGNATURE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string STAN {
            get {
                return this.sTANField;
            }
            set {
                this.sTANField = value;
                this.RaisePropertyChanged("STAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TIME {
            get {
                return this.tIMEField;
            }
            set {
                this.tIMEField = value;
                this.RaisePropertyChanged("TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TRN {
            get {
                return this.tRNField;
            }
            set {
                this.tRNField = value;
                this.RaisePropertyChanged("TRN");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.s2m.messaging/")]
    public partial class saleConfResponse : generalResponse {
        
        private string aMOUNTField;
        
        private string rEPETETIVEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
                this.RaisePropertyChanged("AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string REPETETIVE {
            get {
                return this.rEPETETIVEField;
            }
            set {
                this.rEPETETIVEField = value;
                this.RaisePropertyChanged("REPETETIVE");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendConfirmation", WrapperNamespace="http://ws.s2m.messaging/", IsWrapped=true)]
    public partial class sendConfirmationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.s2m.messaging/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OnlinePayment.MabnaCardVerifyService.confirmationDTO SaleConf_req;
        
        public sendConfirmationRequest() {
        }
        
        public sendConfirmationRequest(OnlinePayment.MabnaCardVerifyService.confirmationDTO SaleConf_req) {
            this.SaleConf_req = SaleConf_req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendConfirmationResponse", WrapperNamespace="http://ws.s2m.messaging/", IsWrapped=true)]
    public partial class sendConfirmationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.s2m.messaging/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OnlinePayment.MabnaCardVerifyService.saleConfResponse @return;
        
        public sendConfirmationResponse() {
        }
        
        public sendConfirmationResponse(OnlinePayment.MabnaCardVerifyService.saleConfResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransactionReferenceChannel : OnlinePayment.MabnaCardVerifyService.TransactionReference, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionReferenceClient : System.ServiceModel.ClientBase<OnlinePayment.MabnaCardVerifyService.TransactionReference>, OnlinePayment.MabnaCardVerifyService.TransactionReference {
        
        public TransactionReferenceClient() {
        }
        
        public TransactionReferenceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionReferenceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionReferenceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionReferenceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlinePayment.MabnaCardVerifyService.sendConfirmationResponse OnlinePayment.MabnaCardVerifyService.TransactionReference.sendConfirmation(OnlinePayment.MabnaCardVerifyService.sendConfirmationRequest request) {
            return base.Channel.sendConfirmation(request);
        }
        
        public OnlinePayment.MabnaCardVerifyService.saleConfResponse sendConfirmation(OnlinePayment.MabnaCardVerifyService.confirmationDTO SaleConf_req) {
            OnlinePayment.MabnaCardVerifyService.sendConfirmationRequest inValue = new OnlinePayment.MabnaCardVerifyService.sendConfirmationRequest();
            inValue.SaleConf_req = SaleConf_req;
            OnlinePayment.MabnaCardVerifyService.sendConfirmationResponse retVal = ((OnlinePayment.MabnaCardVerifyService.TransactionReference)(this)).sendConfirmation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlinePayment.MabnaCardVerifyService.sendConfirmationResponse> OnlinePayment.MabnaCardVerifyService.TransactionReference.sendConfirmationAsync(OnlinePayment.MabnaCardVerifyService.sendConfirmationRequest request) {
            return base.Channel.sendConfirmationAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlinePayment.MabnaCardVerifyService.sendConfirmationResponse> sendConfirmationAsync(OnlinePayment.MabnaCardVerifyService.confirmationDTO SaleConf_req) {
            OnlinePayment.MabnaCardVerifyService.sendConfirmationRequest inValue = new OnlinePayment.MabnaCardVerifyService.sendConfirmationRequest();
            inValue.SaleConf_req = SaleConf_req;
            return ((OnlinePayment.MabnaCardVerifyService.TransactionReference)(this)).sendConfirmationAsync(inValue);
        }
    }
}
