//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.BehPardakht {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BehPardakhtResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BehPardakhtResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlinePayment.BehPardakht.BehPardakhtResource", typeof(BehPardakhtResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش با موفقيت انجام شد.
        /// </summary>
        internal static string plus0 {
            get {
                return ResourceManager.GetString("plus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره كارت نامعتبر است.
        /// </summary>
        internal static string plus11 {
            get {
                return ResourceManager.GetString("plus11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر كننده كارت نامعتبر است.
        /// </summary>
        internal static string plus111 {
            get {
                return ResourceManager.GetString("plus111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاي سوييچ صادر كننده كارت.
        /// </summary>
        internal static string plus112 {
            get {
                return ResourceManager.GetString("plus112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخي از صادر كننده كارت دريافت نشد.
        /// </summary>
        internal static string plus113 {
            get {
                return ResourceManager.GetString("plus113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارنده كارت مجاز به انجام اين تراكنش نيست.
        /// </summary>
        internal static string plus114 {
            get {
                return ResourceManager.GetString("plus114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودي كافي نيست.
        /// </summary>
        internal static string plus12 {
            get {
                return ResourceManager.GetString("plus12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز نادرست است.
        /// </summary>
        internal static string plus13 {
            get {
                return ResourceManager.GetString("plus13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دفعات وارد كردن رمز بيش از حد مجاز است.
        /// </summary>
        internal static string plus14 {
            get {
                return ResourceManager.GetString("plus14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كارت نامعتبر است.
        /// </summary>
        internal static string plus15 {
            get {
                return ResourceManager.GetString("plus15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفعات برداشت وجه بيش از حد مجاز است.
        /// </summary>
        internal static string plus16 {
            get {
                return ResourceManager.GetString("plus16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كاربر از انجام تراكنش منصرف شده است.
        /// </summary>
        internal static string plus17 {
            get {
                return ResourceManager.GetString("plus17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انقضاي كارت گذشته است.
        /// </summary>
        internal static string plus18 {
            get {
                return ResourceManager.GetString("plus18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ برداشت وجه بيش از حد مجاز است.
        /// </summary>
        internal static string plus19 {
            get {
                return ResourceManager.GetString("plus19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذيرنده نامعتبر است.
        /// </summary>
        internal static string plus21 {
            get {
                return ResourceManager.GetString("plus21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاي امنيتي رخ داده است.
        /// </summary>
        internal static string plus23 {
            get {
                return ResourceManager.GetString("plus23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات كاربري پذيرنده نامعتبر است.
        /// </summary>
        internal static string plus24 {
            get {
                return ResourceManager.GetString("plus24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ نامعتبر است.
        /// </summary>
        internal static string plus25 {
            get {
                return ResourceManager.GetString("plus25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ نامعتبر است.
        /// </summary>
        internal static string plus31 {
            get {
                return ResourceManager.GetString("plus31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت اطلاعات وارد شده صحيح نمي باشد.
        /// </summary>
        internal static string plus32 {
            get {
                return ResourceManager.GetString("plus32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب نامعتبر است.
        /// </summary>
        internal static string plus33 {
            get {
                return ResourceManager.GetString("plus33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاي سيستمي.
        /// </summary>
        internal static string plus34 {
            get {
                return ResourceManager.GetString("plus34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نامعتبر است.
        /// </summary>
        internal static string plus35 {
            get {
                return ResourceManager.GetString("plus35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره درخواست تكراري است.
        /// </summary>
        internal static string plus41 {
            get {
                return ResourceManager.GetString("plus41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه قبض نادرست است.
        /// </summary>
        internal static string plus412 {
            get {
                return ResourceManager.GetString("plus412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پرداخت نادرست است.
        /// </summary>
        internal static string plus413 {
            get {
                return ResourceManager.GetString("plus413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان صادر كننده قبض نامعتبر است.
        /// </summary>
        internal static string plus414 {
            get {
                return ResourceManager.GetString("plus414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان جلسه كاري به پايان رسيده است.
        /// </summary>
        internal static string plus415 {
            get {
                return ResourceManager.GetString("plus415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت اطلاعات.
        /// </summary>
        internal static string plus416 {
            get {
                return ResourceManager.GetString("plus416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پرداخت كننده نامعتبر است.
        /// </summary>
        internal static string plus417 {
            get {
                return ResourceManager.GetString("plus417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشكال در تعريف اطلاعات مشتري.
        /// </summary>
        internal static string plus418 {
            get {
                return ResourceManager.GetString("plus418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دفعات ورود اطلاعات از حد مجاز گذشته است.
        /// </summary>
        internal static string plus419 {
            get {
                return ResourceManager.GetString("plus419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يافت نشد Sale تراكنش.
        /// </summary>
        internal static string plus42 {
            get {
                return ResourceManager.GetString("plus42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعتبر است IP.
        /// </summary>
        internal static string plus421 {
            get {
                return ResourceManager.GetString("plus421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده شده است Verify قبلا درخواست.
        /// </summary>
        internal static string plus43 {
            get {
                return ResourceManager.GetString("plus43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يافت نشد Verfiy درخواست.
        /// </summary>
        internal static string plus44 {
            get {
                return ResourceManager.GetString("plus44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شده است Settle تراكنش.
        /// </summary>
        internal static string plus45 {
            get {
                return ResourceManager.GetString("plus45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشده است Settle تراكنش.
        /// </summary>
        internal static string plus46 {
            get {
                return ResourceManager.GetString("plus46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يافت نشد Settle تراكنش.
        /// </summary>
        internal static string plus47 {
            get {
                return ResourceManager.GetString("plus47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شده است Reverse تراكنش.
        /// </summary>
        internal static string plus48 {
            get {
                return ResourceManager.GetString("plus48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يافت نشد Refund تراكنش.
        /// </summary>
        internal static string plus49 {
            get {
                return ResourceManager.GetString("plus49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش تكراري است.
        /// </summary>
        internal static string plus51 {
            get {
                return ResourceManager.GetString("plus51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش مرجع موجود نيست.
        /// </summary>
        internal static string plus54 {
            get {
                return ResourceManager.GetString("plus54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش نامعتبر است.
        /// </summary>
        internal static string plus55 {
            get {
                return ResourceManager.GetString("plus55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در واريز.
        /// </summary>
        internal static string plus61 {
            get {
                return ResourceManager.GetString("plus61", resourceCulture);
            }
        }
    }
}
