//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.AsanPardakhtService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDataPackage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TransactionDataPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FetchResultField;
        
        private System.DateTime ReportDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlinePayment.AsanPardakhtService.TransactionStatus[] TransactionListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FetchResult {
            get {
                return this.FetchResultField;
            }
            set {
                if ((this.FetchResultField.Equals(value) != true)) {
                    this.FetchResultField = value;
                    this.RaisePropertyChanged("FetchResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ReportDate {
            get {
                return this.ReportDateField;
            }
            set {
                if ((this.ReportDateField.Equals(value) != true)) {
                    this.ReportDateField = value;
                    this.RaisePropertyChanged("ReportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public OnlinePayment.AsanPardakhtService.TransactionStatus[] TransactionList {
            get {
                return this.TransactionListField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionListField, value) != true)) {
                    this.TransactionListField = value;
                    this.RaisePropertyChanged("TransactionList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatus", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TransactionStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EMerchantConfigIDField;
        
        private long LocalInvoiceIDField;
        
        private System.DateTime OperationRequestDateField;
        
        private System.DateTime MerchantLocalDateField;
        
        private long RequestedAmountInRialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalDataField;
        
        private int ServiceTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallbackURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        private long PayGateTranIDField;
        
        private System.DateTime TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        private int StanField;
        
        private long ActualTrxAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrxResultCodeField;
        
        private bool MainTrxWasSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RRNField;
        
        private bool IsVerifiedField;
        
        private System.Nullable<System.DateTime> VerifyRequestDateField;
        
        private bool ReconcilationSucceededField;
        
        private System.Nullable<System.DateTime> ReconcilationRequestDateField;
        
        private bool IsReconcilationRequestedAutomaticallyField;
        
        private System.Nullable<System.DateTime> ReconcilationTryDateField;
        
        private bool ReversalSucceededField;
        
        private System.Nullable<System.DateTime> ReversalRequestDateField;
        
        private bool IsReversalRequestedAutomaticallyField;
        
        private System.Nullable<System.DateTime> ReversalTryDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EMerchantConfigID {
            get {
                return this.EMerchantConfigIDField;
            }
            set {
                if ((this.EMerchantConfigIDField.Equals(value) != true)) {
                    this.EMerchantConfigIDField = value;
                    this.RaisePropertyChanged("EMerchantConfigID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long LocalInvoiceID {
            get {
                return this.LocalInvoiceIDField;
            }
            set {
                if ((this.LocalInvoiceIDField.Equals(value) != true)) {
                    this.LocalInvoiceIDField = value;
                    this.RaisePropertyChanged("LocalInvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime OperationRequestDate {
            get {
                return this.OperationRequestDateField;
            }
            set {
                if ((this.OperationRequestDateField.Equals(value) != true)) {
                    this.OperationRequestDateField = value;
                    this.RaisePropertyChanged("OperationRequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime MerchantLocalDate {
            get {
                return this.MerchantLocalDateField;
            }
            set {
                if ((this.MerchantLocalDateField.Equals(value) != true)) {
                    this.MerchantLocalDateField = value;
                    this.RaisePropertyChanged("MerchantLocalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long RequestedAmountInRials {
            get {
                return this.RequestedAmountInRialsField;
            }
            set {
                if ((this.RequestedAmountInRialsField.Equals(value) != true)) {
                    this.RequestedAmountInRialsField = value;
                    this.RaisePropertyChanged("RequestedAmountInRials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AdditionalData {
            get {
                return this.AdditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataField, value) != true)) {
                    this.AdditionalDataField = value;
                    this.RaisePropertyChanged("AdditionalData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int ServiceTypeID {
            get {
                return this.ServiceTypeIDField;
            }
            set {
                if ((this.ServiceTypeIDField.Equals(value) != true)) {
                    this.ServiceTypeIDField = value;
                    this.RaisePropertyChanged("ServiceTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CallbackURL {
            get {
                return this.CallbackURLField;
            }
            set {
                if ((object.ReferenceEquals(this.CallbackURLField, value) != true)) {
                    this.CallbackURLField = value;
                    this.RaisePropertyChanged("CallbackURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PayerID {
            get {
                return this.PayerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PayerIDField, value) != true)) {
                    this.PayerIDField = value;
                    this.RaisePropertyChanged("PayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public long PayGateTranID {
            get {
                return this.PayGateTranIDField;
            }
            set {
                if ((this.PayGateTranIDField.Equals(value) != true)) {
                    this.PayGateTranIDField = value;
                    this.RaisePropertyChanged("PayGateTranID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int Stan {
            get {
                return this.StanField;
            }
            set {
                if ((this.StanField.Equals(value) != true)) {
                    this.StanField = value;
                    this.RaisePropertyChanged("Stan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public long ActualTrxAmount {
            get {
                return this.ActualTrxAmountField;
            }
            set {
                if ((this.ActualTrxAmountField.Equals(value) != true)) {
                    this.ActualTrxAmountField = value;
                    this.RaisePropertyChanged("ActualTrxAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string BillID {
            get {
                return this.BillIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BillIDField, value) != true)) {
                    this.BillIDField = value;
                    this.RaisePropertyChanged("BillID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentIDField, value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string TrxResultCode {
            get {
                return this.TrxResultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TrxResultCodeField, value) != true)) {
                    this.TrxResultCodeField = value;
                    this.RaisePropertyChanged("TrxResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool MainTrxWasSuccessful {
            get {
                return this.MainTrxWasSuccessfulField;
            }
            set {
                if ((this.MainTrxWasSuccessfulField.Equals(value) != true)) {
                    this.MainTrxWasSuccessfulField = value;
                    this.RaisePropertyChanged("MainTrxWasSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string RRN {
            get {
                return this.RRNField;
            }
            set {
                if ((object.ReferenceEquals(this.RRNField, value) != true)) {
                    this.RRNField = value;
                    this.RaisePropertyChanged("RRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool IsVerified {
            get {
                return this.IsVerifiedField;
            }
            set {
                if ((this.IsVerifiedField.Equals(value) != true)) {
                    this.IsVerifiedField = value;
                    this.RaisePropertyChanged("IsVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<System.DateTime> VerifyRequestDate {
            get {
                return this.VerifyRequestDateField;
            }
            set {
                if ((this.VerifyRequestDateField.Equals(value) != true)) {
                    this.VerifyRequestDateField = value;
                    this.RaisePropertyChanged("VerifyRequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public bool ReconcilationSucceeded {
            get {
                return this.ReconcilationSucceededField;
            }
            set {
                if ((this.ReconcilationSucceededField.Equals(value) != true)) {
                    this.ReconcilationSucceededField = value;
                    this.RaisePropertyChanged("ReconcilationSucceeded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.Nullable<System.DateTime> ReconcilationRequestDate {
            get {
                return this.ReconcilationRequestDateField;
            }
            set {
                if ((this.ReconcilationRequestDateField.Equals(value) != true)) {
                    this.ReconcilationRequestDateField = value;
                    this.RaisePropertyChanged("ReconcilationRequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public bool IsReconcilationRequestedAutomatically {
            get {
                return this.IsReconcilationRequestedAutomaticallyField;
            }
            set {
                if ((this.IsReconcilationRequestedAutomaticallyField.Equals(value) != true)) {
                    this.IsReconcilationRequestedAutomaticallyField = value;
                    this.RaisePropertyChanged("IsReconcilationRequestedAutomatically");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public System.Nullable<System.DateTime> ReconcilationTryDate {
            get {
                return this.ReconcilationTryDateField;
            }
            set {
                if ((this.ReconcilationTryDateField.Equals(value) != true)) {
                    this.ReconcilationTryDateField = value;
                    this.RaisePropertyChanged("ReconcilationTryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public bool ReversalSucceeded {
            get {
                return this.ReversalSucceededField;
            }
            set {
                if ((this.ReversalSucceededField.Equals(value) != true)) {
                    this.ReversalSucceededField = value;
                    this.RaisePropertyChanged("ReversalSucceeded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public System.Nullable<System.DateTime> ReversalRequestDate {
            get {
                return this.ReversalRequestDateField;
            }
            set {
                if ((this.ReversalRequestDateField.Equals(value) != true)) {
                    this.ReversalRequestDateField = value;
                    this.RaisePropertyChanged("ReversalRequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public bool IsReversalRequestedAutomatically {
            get {
                return this.IsReversalRequestedAutomaticallyField;
            }
            set {
                if ((this.IsReversalRequestedAutomaticallyField.Equals(value) != true)) {
                    this.IsReversalRequestedAutomaticallyField = value;
                    this.RaisePropertyChanged("IsReversalRequestedAutomatically");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public System.Nullable<System.DateTime> ReversalTryDate {
            get {
                return this.ReversalTryDateField;
            }
            set {
                if ((this.ReversalTryDateField.Equals(value) != true)) {
                    this.ReversalTryDateField = value;
                    this.RaisePropertyChanged("ReversalTryDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsanPardakhtService.merchantservicesSoap")]
    public interface merchantservicesSoap {
        
        // CODEGEN: Generating message contract since element name encryptedRequest from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOperation", ReplyAction="*")]
        OnlinePayment.AsanPardakhtService.RequestOperationResponse RequestOperation(OnlinePayment.AsanPardakhtService.RequestOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestOperationResponse> RequestOperationAsync(OnlinePayment.AsanPardakhtService.RequestOperationRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedCredentials from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestReconciliation", ReplyAction="*")]
        OnlinePayment.AsanPardakhtService.RequestReconciliationResponse RequestReconciliation(OnlinePayment.AsanPardakhtService.RequestReconciliationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestReconciliation", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestReconciliationResponse> RequestReconciliationAsync(OnlinePayment.AsanPardakhtService.RequestReconciliationRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedCredentials from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestVerification", ReplyAction="*")]
        OnlinePayment.AsanPardakhtService.RequestVerificationResponse RequestVerification(OnlinePayment.AsanPardakhtService.RequestVerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestVerificationResponse> RequestVerificationAsync(OnlinePayment.AsanPardakhtService.RequestVerificationRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedCredentials from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestReversal", ReplyAction="*")]
        OnlinePayment.AsanPardakhtService.RequestReversalResponse RequestReversal(OnlinePayment.AsanPardakhtService.RequestReversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestReversal", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestReversalResponse> RequestReversalAsync(OnlinePayment.AsanPardakhtService.RequestReversalRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedCredintials from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrxStatusFromLocalInvoiceID", ReplyAction="*")]
        OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDResponse TrxStatusFromLocalInvoiceID(OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrxStatusFromLocalInvoiceID", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDResponse> TrxStatusFromLocalInvoiceIDAsync(OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOperation", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.RequestOperationRequestBody Body;
        
        public RequestOperationRequest() {
        }
        
        public RequestOperationRequest(OnlinePayment.AsanPardakhtService.RequestOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedRequest;
        
        public RequestOperationRequestBody() {
        }
        
        public RequestOperationRequestBody(int merchantConfigurationID, string encryptedRequest) {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedRequest = encryptedRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOperationResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.RequestOperationResponseBody Body;
        
        public RequestOperationResponse() {
        }
        
        public RequestOperationResponse(OnlinePayment.AsanPardakhtService.RequestOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestOperationResult;
        
        public RequestOperationResponseBody() {
        }
        
        public RequestOperationResponseBody(string RequestOperationResult) {
            this.RequestOperationResult = RequestOperationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestReconciliationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestReconciliation", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.RequestReconciliationRequestBody Body;
        
        public RequestReconciliationRequest() {
        }
        
        public RequestReconciliationRequest(OnlinePayment.AsanPardakhtService.RequestReconciliationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestReconciliationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedCredentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong payGateTranID;
        
        public RequestReconciliationRequestBody() {
        }
        
        public RequestReconciliationRequestBody(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedCredentials = encryptedCredentials;
            this.payGateTranID = payGateTranID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestReconciliationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestReconciliationResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.RequestReconciliationResponseBody Body;
        
        public RequestReconciliationResponse() {
        }
        
        public RequestReconciliationResponse(OnlinePayment.AsanPardakhtService.RequestReconciliationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestReconciliationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestReconciliationResult;
        
        public RequestReconciliationResponseBody() {
        }
        
        public RequestReconciliationResponseBody(string RequestReconciliationResult) {
            this.RequestReconciliationResult = RequestReconciliationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestVerificationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestVerification", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.RequestVerificationRequestBody Body;
        
        public RequestVerificationRequest() {
        }
        
        public RequestVerificationRequest(OnlinePayment.AsanPardakhtService.RequestVerificationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestVerificationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedCredentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong payGateTranID;
        
        public RequestVerificationRequestBody() {
        }
        
        public RequestVerificationRequestBody(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedCredentials = encryptedCredentials;
            this.payGateTranID = payGateTranID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestVerificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestVerificationResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.RequestVerificationResponseBody Body;
        
        public RequestVerificationResponse() {
        }
        
        public RequestVerificationResponse(OnlinePayment.AsanPardakhtService.RequestVerificationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestVerificationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestVerificationResult;
        
        public RequestVerificationResponseBody() {
        }
        
        public RequestVerificationResponseBody(string RequestVerificationResult) {
            this.RequestVerificationResult = RequestVerificationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestReversalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestReversal", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.RequestReversalRequestBody Body;
        
        public RequestReversalRequest() {
        }
        
        public RequestReversalRequest(OnlinePayment.AsanPardakhtService.RequestReversalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestReversalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedCredentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong payGateTranID;
        
        public RequestReversalRequestBody() {
        }
        
        public RequestReversalRequestBody(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedCredentials = encryptedCredentials;
            this.payGateTranID = payGateTranID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestReversalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestReversalResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.RequestReversalResponseBody Body;
        
        public RequestReversalResponse() {
        }
        
        public RequestReversalResponse(OnlinePayment.AsanPardakhtService.RequestReversalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestReversalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestReversalResult;
        
        public RequestReversalResponseBody() {
        }
        
        public RequestReversalResponseBody(string RequestReversalResult) {
            this.RequestReversalResult = RequestReversalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrxStatusFromLocalInvoiceIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrxStatusFromLocalInvoiceID", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequestBody Body;
        
        public TrxStatusFromLocalInvoiceIDRequest() {
        }
        
        public TrxStatusFromLocalInvoiceIDRequest(OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrxStatusFromLocalInvoiceIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedCredintials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long localInvoiceID;
        
        public TrxStatusFromLocalInvoiceIDRequestBody() {
        }
        
        public TrxStatusFromLocalInvoiceIDRequestBody(int merchantConfigurationID, string encryptedCredintials, long localInvoiceID) {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedCredintials = encryptedCredintials;
            this.localInvoiceID = localInvoiceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrxStatusFromLocalInvoiceIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrxStatusFromLocalInvoiceIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDResponseBody Body;
        
        public TrxStatusFromLocalInvoiceIDResponse() {
        }
        
        public TrxStatusFromLocalInvoiceIDResponse(OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrxStatusFromLocalInvoiceIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnlinePayment.AsanPardakhtService.TransactionDataPackage TrxStatusFromLocalInvoiceIDResult;
        
        public TrxStatusFromLocalInvoiceIDResponseBody() {
        }
        
        public TrxStatusFromLocalInvoiceIDResponseBody(OnlinePayment.AsanPardakhtService.TransactionDataPackage TrxStatusFromLocalInvoiceIDResult) {
            this.TrxStatusFromLocalInvoiceIDResult = TrxStatusFromLocalInvoiceIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface merchantservicesSoapChannel : OnlinePayment.AsanPardakhtService.merchantservicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class merchantservicesSoapClient : System.ServiceModel.ClientBase<OnlinePayment.AsanPardakhtService.merchantservicesSoap>, OnlinePayment.AsanPardakhtService.merchantservicesSoap {
        
        public merchantservicesSoapClient() {
        }
        
        public merchantservicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public merchantservicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public merchantservicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public merchantservicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlinePayment.AsanPardakhtService.RequestOperationResponse OnlinePayment.AsanPardakhtService.merchantservicesSoap.RequestOperation(OnlinePayment.AsanPardakhtService.RequestOperationRequest request) {
            return base.Channel.RequestOperation(request);
        }
        
        public string RequestOperation(int merchantConfigurationID, string encryptedRequest) {
            OnlinePayment.AsanPardakhtService.RequestOperationRequest inValue = new OnlinePayment.AsanPardakhtService.RequestOperationRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.RequestOperationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedRequest = encryptedRequest;
            OnlinePayment.AsanPardakhtService.RequestOperationResponse retVal = ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).RequestOperation(inValue);
            return retVal.Body.RequestOperationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestOperationResponse> OnlinePayment.AsanPardakhtService.merchantservicesSoap.RequestOperationAsync(OnlinePayment.AsanPardakhtService.RequestOperationRequest request) {
            return base.Channel.RequestOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestOperationResponse> RequestOperationAsync(int merchantConfigurationID, string encryptedRequest) {
            OnlinePayment.AsanPardakhtService.RequestOperationRequest inValue = new OnlinePayment.AsanPardakhtService.RequestOperationRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.RequestOperationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedRequest = encryptedRequest;
            return ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).RequestOperationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlinePayment.AsanPardakhtService.RequestReconciliationResponse OnlinePayment.AsanPardakhtService.merchantservicesSoap.RequestReconciliation(OnlinePayment.AsanPardakhtService.RequestReconciliationRequest request) {
            return base.Channel.RequestReconciliation(request);
        }
        
        public string RequestReconciliation(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            OnlinePayment.AsanPardakhtService.RequestReconciliationRequest inValue = new OnlinePayment.AsanPardakhtService.RequestReconciliationRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.RequestReconciliationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            OnlinePayment.AsanPardakhtService.RequestReconciliationResponse retVal = ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).RequestReconciliation(inValue);
            return retVal.Body.RequestReconciliationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestReconciliationResponse> OnlinePayment.AsanPardakhtService.merchantservicesSoap.RequestReconciliationAsync(OnlinePayment.AsanPardakhtService.RequestReconciliationRequest request) {
            return base.Channel.RequestReconciliationAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestReconciliationResponse> RequestReconciliationAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            OnlinePayment.AsanPardakhtService.RequestReconciliationRequest inValue = new OnlinePayment.AsanPardakhtService.RequestReconciliationRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.RequestReconciliationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            return ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).RequestReconciliationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlinePayment.AsanPardakhtService.RequestVerificationResponse OnlinePayment.AsanPardakhtService.merchantservicesSoap.RequestVerification(OnlinePayment.AsanPardakhtService.RequestVerificationRequest request) {
            return base.Channel.RequestVerification(request);
        }
        
        public string RequestVerification(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            OnlinePayment.AsanPardakhtService.RequestVerificationRequest inValue = new OnlinePayment.AsanPardakhtService.RequestVerificationRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.RequestVerificationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            OnlinePayment.AsanPardakhtService.RequestVerificationResponse retVal = ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).RequestVerification(inValue);
            return retVal.Body.RequestVerificationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestVerificationResponse> OnlinePayment.AsanPardakhtService.merchantservicesSoap.RequestVerificationAsync(OnlinePayment.AsanPardakhtService.RequestVerificationRequest request) {
            return base.Channel.RequestVerificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestVerificationResponse> RequestVerificationAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            OnlinePayment.AsanPardakhtService.RequestVerificationRequest inValue = new OnlinePayment.AsanPardakhtService.RequestVerificationRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.RequestVerificationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            return ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).RequestVerificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlinePayment.AsanPardakhtService.RequestReversalResponse OnlinePayment.AsanPardakhtService.merchantservicesSoap.RequestReversal(OnlinePayment.AsanPardakhtService.RequestReversalRequest request) {
            return base.Channel.RequestReversal(request);
        }
        
        public string RequestReversal(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            OnlinePayment.AsanPardakhtService.RequestReversalRequest inValue = new OnlinePayment.AsanPardakhtService.RequestReversalRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.RequestReversalRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            OnlinePayment.AsanPardakhtService.RequestReversalResponse retVal = ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).RequestReversal(inValue);
            return retVal.Body.RequestReversalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestReversalResponse> OnlinePayment.AsanPardakhtService.merchantservicesSoap.RequestReversalAsync(OnlinePayment.AsanPardakhtService.RequestReversalRequest request) {
            return base.Channel.RequestReversalAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.RequestReversalResponse> RequestReversalAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID) {
            OnlinePayment.AsanPardakhtService.RequestReversalRequest inValue = new OnlinePayment.AsanPardakhtService.RequestReversalRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.RequestReversalRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            return ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).RequestReversalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDResponse OnlinePayment.AsanPardakhtService.merchantservicesSoap.TrxStatusFromLocalInvoiceID(OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequest request) {
            return base.Channel.TrxStatusFromLocalInvoiceID(request);
        }
        
        public OnlinePayment.AsanPardakhtService.TransactionDataPackage TrxStatusFromLocalInvoiceID(int merchantConfigurationID, string encryptedCredintials, long localInvoiceID) {
            OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequest inValue = new OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredintials = encryptedCredintials;
            inValue.Body.localInvoiceID = localInvoiceID;
            OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDResponse retVal = ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).TrxStatusFromLocalInvoiceID(inValue);
            return retVal.Body.TrxStatusFromLocalInvoiceIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDResponse> OnlinePayment.AsanPardakhtService.merchantservicesSoap.TrxStatusFromLocalInvoiceIDAsync(OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequest request) {
            return base.Channel.TrxStatusFromLocalInvoiceIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDResponse> TrxStatusFromLocalInvoiceIDAsync(int merchantConfigurationID, string encryptedCredintials, long localInvoiceID) {
            OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequest inValue = new OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequest();
            inValue.Body = new OnlinePayment.AsanPardakhtService.TrxStatusFromLocalInvoiceIDRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredintials = encryptedCredintials;
            inValue.Body.localInvoiceID = localInvoiceID;
            return ((OnlinePayment.AsanPardakhtService.merchantservicesSoap)(this)).TrxStatusFromLocalInvoiceIDAsync(inValue);
        }
    }
}
