//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.SadadSwitch1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SadadResourceSwitch1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SadadResourceSwitch1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlinePayment.SadadSwitch1.SadadResourceSwitch1", typeof(SadadResourceSwitch1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجه استعلام نامعلوم. پارامترهای ارسالی صحيح نيست و یا تراکنش در سيستم وجود ندارد..
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش با موفقیت انجام شد..
        /// </summary>
        internal static string plus0 {
            get {
                return ResourceManager.GetString("plus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا با بانک صادر کننده کارت، تماس حاصل فرمائيد.
        /// </summary>
        internal static string plus1 {
            get {
                return ResourceManager.GetString("plus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب پارامترهای ارسالی اشتباه می باشد، لطفا مسئول فنی پذیرنده با بانک تماس حاصل فرمایند.
        /// </summary>
        internal static string plus1000 {
            get {
                return ResourceManager.GetString("plus1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مسئول فنی پذیرنده با بانک تماس حاصل فرمایند،پارامترهای پرداخت اشتباه می باشد.
        /// </summary>
        internal static string plus1001 {
            get {
                return ResourceManager.GetString("plus1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سيستم تراکنش ناموفق.
        /// </summary>
        internal static string plus1002 {
            get {
                return ResourceManager.GetString("plus1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP پذیرنده اشتباه است.لطفا مسئول فنی پذیرنده با بانک تماس حاصل فرمایند.
        /// </summary>
        internal static string plus1003 {
            get {
                return ResourceManager.GetString("plus1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مسئول فنی پذیرنده با بانک تماس حاصل فرمایند،شماره پذیرنده اشتباه است.
        /// </summary>
        internal static string plus1004 {
            get {
                return ResourceManager.GetString("plus1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای دسترسی:لطفا بعدا تلاش فرمایيد.
        /// </summary>
        internal static string plus1005 {
            get {
                return ResourceManager.GetString("plus1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سيستم.
        /// </summary>
        internal static string plus1006 {
            get {
                return ResourceManager.GetString("plus1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تكراری شماره سفارش تكراری می باشد.
        /// </summary>
        internal static string plus1011 {
            get {
                return ResourceManager.GetString("plus1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پذیرنده صحيح نيست،یكی از موارد تاریخ،زمان یا کليد تراکنش اشتباه است.لطفا مسئول فنی پذیرنده با بانک تماس حاصل فرمایند.
        /// </summary>
        internal static string plus1012 {
            get {
                return ResourceManager.GetString("plus1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ خطای نامشخص از سمت مرکز.
        /// </summary>
        internal static string plus1015 {
            get {
                return ResourceManager.GetString("plus1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت با کارتهای شتاب غير فعال شده است.
        /// </summary>
        internal static string plus1016 {
            get {
                return ResourceManager.GetString("plus1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی شما جهت پرداخت از حد مجاز تعریف شده برای این پذیرنده بيشتر است.
        /// </summary>
        internal static string plus1017 {
            get {
                return ResourceManager.GetString("plus1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشكال در تاریخ و زمان سيستم. لطفا تاریخ و زمان سرور خود را با بانک هماهنگ نمایيد.
        /// </summary>
        internal static string plus1018 {
            get {
                return ResourceManager.GetString("plus1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان پرداخت از طریق سيستم شتاب برای این پذیرنده امكان پذیر نيست.
        /// </summary>
        internal static string plus1019 {
            get {
                return ResourceManager.GetString("plus1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده غيرفعال شده است.لطفا جهت فعال سازی با بانک تماس بگيرید.
        /// </summary>
        internal static string plus1020 {
            get {
                return ResourceManager.GetString("plus1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ورودی جهت پرداخت با آدرس بازگشت پذیرنده مطابقت ندارد.
        /// </summary>
        internal static string plus1022 {
            get {
                return ResourceManager.GetString("plus1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس بازگشت پذیرنده نامعتبر است.
        /// </summary>
        internal static string plus1023 {
            get {
                return ResourceManager.GetString("plus1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهر زمانی پذیرنده نامعتبر است.
        /// </summary>
        internal static string plus1024 {
            get {
                return ResourceManager.GetString("plus1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امضا تراکنش نامعتبر است.
        /// </summary>
        internal static string plus1025 {
            get {
                return ResourceManager.GetString("plus1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفارش تراکنش نامعتبر است.
        /// </summary>
        internal static string plus1026 {
            get {
                return ResourceManager.GetString("plus1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پذیرنده نامعتبر است.
        /// </summary>
        internal static string plus1027 {
            get {
                return ResourceManager.GetString("plus1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ترمينال پذیرنده نامعتبر است.
        /// </summary>
        internal static string plus1028 {
            get {
                return ResourceManager.GetString("plus1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس IP پرداخت در محدوده آدرس های معتبر اعلام شده توسط پذیرنده نيست .لطفا مسئول فنی پذیرنده با بانک تماس حاصل فرمایند.
        /// </summary>
        internal static string plus1029 {
            get {
                return ResourceManager.GetString("plus1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس Domain پرداخت در محدوده آدرس های معتبر اعلام شده توسط پذیرنده نيست .لطفا مسئول فنی پذیرنده با بانک تماس حاصل فرمایند.
        /// </summary>
        internal static string plus1030 {
            get {
                return ResourceManager.GetString("plus1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت زمانی شما جهت پرداخت به پایان رسيده است.لطفا مجددا سعی بفرمایيد.
        /// </summary>
        internal static string plus1031 {
            get {
                return ResourceManager.GetString("plus1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت با این کارت . برای پذیرنده مورد نظر شما امكان پذیر نيست.لطفا از کارتهای مجاز که توسط پذیرنده معرفی شده است . استفاده نمایيد..
        /// </summary>
        internal static string plus1032 {
            get {
                return ResourceManager.GetString("plus1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به علت مشكل در سایت پذیرنده. پرداخت برای این پذیرنده غيرفعال شده است.لطفا مسوول فنی سایت پذیرنده با بانک تماس حاصل فرمایند..
        /// </summary>
        internal static string plus1033 {
            get {
                return ResourceManager.GetString("plus1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات اضافی ارسال نشده یا دارای اشكال است.
        /// </summary>
        internal static string plus1036 {
            get {
                return ResourceManager.GetString("plus1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پذیرنده یا شماره ترمينال پذیرنده صحيح نميباشد.
        /// </summary>
        internal static string plus1037 {
            get {
                return ResourceManager.GetString("plus1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا: درخواست معتبر، از سمت پذیرنده صورت نگرفته است لطفا اطلاعات پذیرنده خود را چک کنيد..
        /// </summary>
        internal static string plus1053 {
            get {
                return ResourceManager.GetString("plus1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار غيرمجاز در ورود اطلاعات.
        /// </summary>
        internal static string plus1055 {
            get {
                return ResourceManager.GetString("plus1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيستم موقتا قطع ميباشد.لطفا بعدا تلاش فرمایيد..
        /// </summary>
        internal static string plus1056 {
            get {
                return ResourceManager.GetString("plus1056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا تراکنش مورد نظر بصورت موفق انجام شده است.
        /// </summary>
        internal static string plus1057 {
            get {
                return ResourceManager.GetString("plus1057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس پرداخت اینترنتی خارج از سرویس می باشد.لطفا بعدا سعی بفرمایيد..
        /// </summary>
        internal static string plus1058 {
            get {
                return ResourceManager.GetString("plus1058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشكال در توليد کد یكتا. لطفا مرورگر خود را بسته و با اجرای مجدد مرورگر عمليات پرداخت را انجام دهيد.
        /// </summary>
        internal static string plus1061 {
            get {
                return ResourceManager.GetString("plus1061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس پرداخت اینترنتی بعلت انجام عمليات بانكی موقتا خارج از سرویس است.لطفا بعدا سعی بفرمایيد.
        /// </summary>
        internal static string plus1063 {
            get {
                return ResourceManager.GetString("plus1063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مجددا سعی بفرمایيد.
        /// </summary>
        internal static string plus1064 {
            get {
                return ResourceManager.GetString("plus1064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط ناموفق .لطفا چند لحظه دیگر مجددا سعی کنيد.
        /// </summary>
        internal static string plus1065 {
            get {
                return ResourceManager.GetString("plus1065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيستم سرویس دهی پرداخت موقتا غير فعال شده است.
        /// </summary>
        internal static string plus1066 {
            get {
                return ResourceManager.GetString("plus1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش به علت بروزرسانی . سيستم موقتا قطع ميباشد.
        /// </summary>
        internal static string plus1068 {
            get {
                return ResourceManager.GetString("plus1068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت خاص ارسالی از طرف پذیرنده جهت پرداخت شما نامعتبر است.لطفا با پذیرنده تماس حاصل فرمایيد..
        /// </summary>
        internal static string plus1070 {
            get {
                return ResourceManager.GetString("plus1070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت شما به عنوان کارت خاص از سوی پذیرنده اعلام شده است و پرداخت مستقيم از طریف این کارت امكان پذیر نيست..
        /// </summary>
        internal static string plus1071 {
            get {
                return ResourceManager.GetString("plus1071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پردازش پارامترهای اختياری پذیرنده.
        /// </summary>
        internal static string plus1072 {
            get {
                return ResourceManager.GetString("plus1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایميل نامعتبر است.
        /// </summary>
        internal static string plus1073 {
            get {
                return ResourceManager.GetString("plus1073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عبارت وارد شده با متن موجود در تصویر یكسان نمی باشد..
        /// </summary>
        internal static string plus1080 {
            get {
                return ResourceManager.GetString("plus1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت شناخته شده نيست.
        /// </summary>
        internal static string plus14 {
            get {
                return ResourceManager.GetString("plus14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده کارت فعال نيست لطفا با بخش امور پذیرندگان، تماس حاصل فرمائيد.
        /// </summary>
        internal static string plus23 {
            get {
                return ResourceManager.GetString("plus23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده کارت فعال نيست لطفا با بخش امور پذیرندگان، تماس حاصل فرمائيد.
        /// </summary>
        internal static string plus3 {
            get {
                return ResourceManager.GetString("plus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده توسط سوئيچ پشتيبانی نمی شود.
        /// </summary>
        internal static string plus31 {
            get {
                return ResourceManager.GetString("plus31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت شما منقضی شده است لطفا برای کارت جدید به شعبه مراجعه فرمائيد.
        /// </summary>
        internal static string plus33 {
            get {
                return ResourceManager.GetString("plus33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دفعات ورود رمز نادرست بيش از حد مجاز است. لطفا از طریق خودپرداز بانک صادرکننده کارت نسبت به تخصيص رمز دوم جدید اقدام نمایيد..
        /// </summary>
        internal static string plus38 {
            get {
                return ResourceManager.GetString("plus38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت مفقوده می باشد لطفا به شعبه خود، مراجعه فرمائيد.
        /// </summary>
        internal static string plus41 {
            get {
                return ResourceManager.GetString("plus41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت مسروقه می باشد لطفا به شعبه خود، مراجعه فرمائيد.
        /// </summary>
        internal static string plus43 {
            get {
                return ResourceManager.GetString("plus43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات قبض صحيح نيست.
        /// </summary>
        internal static string plus44 {
            get {
                return ResourceManager.GetString("plus44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این قبض قبلا پرداخت شده است.
        /// </summary>
        internal static string plus48 {
            get {
                return ResourceManager.GetString("plus48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی از موجودی حساب شما، بيشتر است . حداقل مانده حساب شما پس از عمليات پرداخت باید 100،000 ریال باشد..
        /// </summary>
        internal static string plus51 {
            get {
                return ResourceManager.GetString("plus51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب نامعتبر است.
        /// </summary>
        internal static string plus52 {
            get {
                return ResourceManager.GetString("plus52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضای کارت سپری شده است.
        /// </summary>
        internal static string plus54 {
            get {
                return ResourceManager.GetString("plus54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز کارت صحيح نمی باشد لطفا مجددا، سعی فرمائيد.
        /// </summary>
        internal static string plus55 {
            get {
                return ResourceManager.GetString("plus55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت نامعتبر است.
        /// </summary>
        internal static string plus56 {
            get {
                return ResourceManager.GetString("plus56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارنده کارت مجاز به انجام این تراکنش نمی باشد.
        /// </summary>
        internal static string plus57 {
            get {
                return ResourceManager.GetString("plus57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام تراکنش مربوطه توسط پایانه ی انجام دهنده مجاز نمی باشد ..
        /// </summary>
        internal static string plus58 {
            get {
                return ResourceManager.GetString("plus58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش از حد مجاز بالاتر است.
        /// </summary>
        internal static string plus61 {
            get {
                return ResourceManager.GetString("plus61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت محدود شده است.
        /// </summary>
        internal static string plus62 {
            get {
                return ResourceManager.GetString("plus62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دفعات تراکنش از حد مجاز بيشتر است.
        /// </summary>
        internal static string plus65 {
            get {
                return ResourceManager.GetString("plus65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود رمز دوم کارت از حد مجاز گذشته است. انجام تراکنش اینترنتی از کارت شما امكان پذیر نمی باشد، لطفا با مراجعه به خودپرداز مجددا رمز اینترنتی دریافت فرمائيد.
        /// </summary>
        internal static string plus75 {
            get {
                return ResourceManager.GetString("plus75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز مالی تراکنش نا معتبر است یا مهلت زمان ارسال اصلاحيه به پایان رسيده است ..
        /// </summary>
        internal static string plus77 {
            get {
                return ResourceManager.GetString("plus77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت غير فعال میباشد.
        /// </summary>
        internal static string plus78 {
            get {
                return ResourceManager.GetString("plus78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب متصل به کارت نا معتبر است یا دارای اشكال است.
        /// </summary>
        internal static string plus79 {
            get {
                return ResourceManager.GetString("plus79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارائه دهنده ی خدمات پرداخت یا سامانه شاپرک اعلام Sign Off نموده است . ، لطفا چند دقيقه دیگر مجددا سعی بفرمائيد.
        /// </summary>
        internal static string plus83 {
            get {
                return ResourceManager.GetString("plus83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعيت سامانه ی یا بانک مقصد تراکنش غيرفعال می باشد ) Host Down ).
        /// </summary>
        internal static string plus84 {
            get {
                return ResourceManager.GetString("plus84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موسسه ارسال کننده شاپرک یا مقصد تراکنش در حالت Sign off است.
        /// </summary>
        internal static string plus86 {
            get {
                return ResourceManager.GetString("plus86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه مقصد تراکنش درحال انجام عمليات پایان روز می باشد لطفا چند دقيقه دیگر مجددا سعی بفرمائيد.
        /// </summary>
        internal static string plus90 {
            get {
                return ResourceManager.GetString("plus90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تراکنش در سيستم ثبت شده ولی تراکنش هنوز شروع نشده است..
        /// </summary>
        internal static string plus9000 {
            get {
                return ResourceManager.GetString("plus9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش در سيستم ثبت شده و پيام مالی به سيستم بانک ارسال شده است اما هنوز پاسخی دریافت نشده است..
        /// </summary>
        internal static string plus9001 {
            get {
                return ResourceManager.GetString("plus9001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيستم در حال تلاش جهت برگشت تراکنش خرید است..
        /// </summary>
        internal static string plus9004 {
            get {
                return ResourceManager.GetString("plus9004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيستم در حال تلاش جهت برگشت تراکنش خرید است..
        /// </summary>
        internal static string plus9005 {
            get {
                return ResourceManager.GetString("plus9005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش ناموفق بوده و مبلغ با موفقيت به حساب مشتری برگشت خورده است..
        /// </summary>
        internal static string plus9006 {
            get {
                return ResourceManager.GetString("plus9006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در هنگام انجام عمليات CheckStatus مشكلی رخ داده است. )در اغلب موارد به دليل وجود اشكال در پارامترهای ارسالی(.
        /// </summary>
        internal static string plus9008 {
            get {
                return ResourceManager.GetString("plus9008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيستم در حال تلاش برای دریافت جواب عمليات بانكی است..
        /// </summary>
        internal static string plus9009 {
            get {
                return ResourceManager.GetString("plus9009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش به ليست تراکنشهای برگشت خودکار اضافه شده است و در انتظار برگشت ميباشد..
        /// </summary>
        internal static string plus9010 {
            get {
                return ResourceManager.GetString("plus9010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش برگشت خرید ارسال شده است اما پاسخ دریافت شده قطعی نيست و تراکنش در ليست تراکنشهای معوق ميباشد و نتيجه عمليات بانكی ظرف 24 ساعت آینده مشخص خواهد شد..
        /// </summary>
        internal static string plus9011 {
            get {
                return ResourceManager.GetString("plus9011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجه تراکنش معوق پس از 24 ساعت مشخص شده و این تراکنش ناموفق بوده و به حساب مشتری بازگشت داده شده است..
        /// </summary>
        internal static string plus9012 {
            get {
                return ResourceManager.GetString("plus9012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادرکننده یا سوئيچ مقصد فعال نمی باشد )مدت زمان انتظار برای دریافت پاسخ پایان یافته است(.
        /// </summary>
        internal static string plus91 {
            get {
                return ResourceManager.GetString("plus91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر کننده کارت معتبر نيست.
        /// </summary>
        internal static string plus92 {
            get {
                return ResourceManager.GetString("plus92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش با موفقيت انجام نشد )کمبود منابع و نقض موارد قانونی( لطفا چند دقيقه دیگر مجددا سعی بفرمائيد.
        /// </summary>
        internal static string plus93 {
            get {
                return ResourceManager.GetString("plus93", resourceCulture);
            }
        }
    }
}
