//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.MabnaCard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MabnaCardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MabnaCardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlinePayment.MabnaCard.MabnaCardResource", typeof(MabnaCardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز خطا در امضای دیجیتالی..
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی به وب سرویس پرداخت از آدرس آی پی غیر مجاز صورت گرفته است..
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با شکست مواجه شد. لطفا دوباره تلاش کنید..
        /// </summary>
        internal static string _30000 {
            get {
                return ResourceManager.GetString("_30000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد..
        /// </summary>
        internal static string plus0 {
            get {
                return ResourceManager.GetString("plus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد..
        /// </summary>
        internal static string plus00 {
            get {
                return ResourceManager.GetString("plus00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وجود خطا در فرمت اطلاعات ارسالي.
        /// </summary>
        internal static string plus1 {
            get {
                return ResourceManager.GetString("plus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد..
        /// </summary>
        internal static string plus101 {
            get {
                return ResourceManager.GetString("plus101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش مورد نظر برگشت خورده است..
        /// </summary>
        internal static string plus102 {
            get {
                return ResourceManager.GetString("plus102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائيد انجام نشد..
        /// </summary>
        internal static string plus103 {
            get {
                return ResourceManager.GetString("plus103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پيامي از سوئيچ پرداخت دريافت نشد..
        /// </summary>
        internal static string plus106 {
            get {
                return ResourceManager.GetString("plus106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش درخواستي موجود نيست..
        /// </summary>
        internal static string plus107 {
            get {
                return ResourceManager.GetString("plus107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشكل در ارتباط با سوئيچ.
        /// </summary>
        internal static string plus111 {
            get {
                return ResourceManager.GetString("plus111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقادير ارسالي در درخواست معتبر نيستند..
        /// </summary>
        internal static string plus112 {
            get {
                return ResourceManager.GetString("plus112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاي سمت سرور ( مربوط به واحد فني PSP).
        /// </summary>
        internal static string plus113 {
            get {
                return ResourceManager.GetString("plus113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم وجود پذيرنده و ترمينال مورد درخواست در سيستم.
        /// </summary>
        internal static string plus2 {
            get {
                return ResourceManager.GetString("plus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد درخواست به علت دريافت درخواست توسط آدرس آي پي نامعتبر.
        /// </summary>
        internal static string plus3 {
            get {
                return ResourceManager.GetString("plus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذيرنده مورد نظر امكان استفاده از سيستم را ندارد..
        /// </summary>
        internal static string plus4 {
            get {
                return ResourceManager.GetString("plus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برخورد با مشكل در انجام درخواست مورد نظر.
        /// </summary>
        internal static string plus5 {
            get {
                return ResourceManager.GetString("plus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پردازش درخواست.
        /// </summary>
        internal static string plus6 {
            get {
                return ResourceManager.GetString("plus6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز خطا در تشخيص اصالت اطلاعات (امضاي ديجيتالي نامعتبر است).
        /// </summary>
        internal static string plus7 {
            get {
                return ResourceManager.GetString("plus7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره خريد ارائه شده توسط پذيرنده (شماره CRN) تکراری می باشد.
        /// </summary>
        internal static string plus8 {
            get {
                return ResourceManager.GetString("plus8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيستم در حال حاضر قادر به سرويس دهي نمي باشد. ( اين پيام هنگام بروز رساني سرور برگردانده ميشود.).
        /// </summary>
        internal static string plus9 {
            get {
                return ResourceManager.GetString("plus9", resourceCulture);
            }
        }
    }
}
