//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.Sadad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SadadResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SadadResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlinePayment.Sadad.SadadResource", typeof(SadadResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامترهای ارسالی صحیح نیست و يا تراکنش در سیستم وجود ندارد.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش با موفقیت انجام شد..
        /// </summary>
        internal static string plus0 {
            get {
                return ResourceManager.GetString("plus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب پارامترهای ارسالی اشتباه می باشد, لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string plus1000 {
            get {
                return ResourceManager.GetString("plus1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند,پارامترهای پرداخت اشتباه می باشد.
        /// </summary>
        internal static string plus1001 {
            get {
                return ResourceManager.GetString("plus1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سیستم- تراکنش ناموفق.
        /// </summary>
        internal static string plus1002 {
            get {
                return ResourceManager.GetString("plus1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP پذيرنده اشتباه است.لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string plus1003 {
            get {
                return ResourceManager.GetString("plus1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند,شماره پذيرنده اشتباه است.
        /// </summary>
        internal static string plus1004 {
            get {
                return ResourceManager.GetString("plus1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای دسترسی:لطفا بعدا تلاش فرمايید.
        /// </summary>
        internal static string plus1005 {
            get {
                return ResourceManager.GetString("plus1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سیستم.
        /// </summary>
        internal static string plus1006 {
            get {
                return ResourceManager.GetString("plus1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت ارسال تراکنش به پايان رسیده است.
        /// </summary>
        internal static string plus101 {
            get {
                return ResourceManager.GetString("plus101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تکراری- شماره سفارش تکراری می باشد.
        /// </summary>
        internal static string plus1011 {
            get {
                return ResourceManager.GetString("plus1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پذيرنده صحیح نیست,يکی از موارد تاريخ,زمان يا کلید تراکنش اشتباه است.لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string plus1012 {
            get {
                return ResourceManager.GetString("plus1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ خطای نامشخص از سمت مرکز.
        /// </summary>
        internal static string plus1015 {
            get {
                return ResourceManager.GetString("plus1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی شما جهت پرداخت از حد مجاز تعريف شده برای اين پذيرنده بیشتر است.
        /// </summary>
        internal static string plus1017 {
            get {
                return ResourceManager.GetString("plus1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکال در تاريخ و زمان سیستم. لطفا تاريخ و زمان سرور خود را با بانک هماهنگ نمايید.
        /// </summary>
        internal static string plus1018 {
            get {
                return ResourceManager.GetString("plus1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان پرداخت از طريق سیستم شتاب برای اين پذيرنده امکان پذير نیست.
        /// </summary>
        internal static string plus1019 {
            get {
                return ResourceManager.GetString("plus1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذيرنده غیرفعال شده است.لطفا جهت فعال سازی با بانک تماس بگیريد.
        /// </summary>
        internal static string plus1020 {
            get {
                return ResourceManager.GetString("plus1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس بازگشت پذيرنده نامعتبر است.
        /// </summary>
        internal static string plus1023 {
            get {
                return ResourceManager.GetString("plus1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهر زمانی پذيرنده نامعتبر است.
        /// </summary>
        internal static string plus1024 {
            get {
                return ResourceManager.GetString("plus1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امضا تراکنش نامعتبر است.
        /// </summary>
        internal static string plus1025 {
            get {
                return ResourceManager.GetString("plus1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفارش تراکنش نامعتبر است.
        /// </summary>
        internal static string plus1026 {
            get {
                return ResourceManager.GetString("plus1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پذيرنده نامعتبر است.
        /// </summary>
        internal static string plus1027 {
            get {
                return ResourceManager.GetString("plus1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ترمینال پذيرنده نامعتبر است.
        /// </summary>
        internal static string plus1028 {
            get {
                return ResourceManager.GetString("plus1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس IP پرداخت در محدوده آدرس های معتبر اعلام شده توسط پذيرنده نیست .لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string plus1029 {
            get {
                return ResourceManager.GetString("plus1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس Domain پرداخت در محدوده آدرس های معتبر اعلام شده توسط پذيرنده نیست .لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string plus1030 {
            get {
                return ResourceManager.GetString("plus1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت زمانی شما جهت پرداخت به پايان رسیده است.لطفا مجددا سعی بفرمايید.
        /// </summary>
        internal static string plus1031 {
            get {
                return ResourceManager.GetString("plus1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت با اين کارت . برای پذيرنده مورد نظر شما امکان پذير نیست.لطفا از کارتهای مجاز که توسط پذيرنده معرفی شده است . استفاده نمايید.
        /// </summary>
        internal static string plus1032 {
            get {
                return ResourceManager.GetString("plus1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به علت مشکل در سايت پذيرنده. پرداخت برای اين پذيرنده غیرفعال شده است.لطفا مسوول فنی سايت پذيرنده با بانک تماس حاصل فرمايند..
        /// </summary>
        internal static string plus1033 {
            get {
                return ResourceManager.GetString("plus1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات اضافی ارسال نشده يا دارای اشکال است.
        /// </summary>
        internal static string plus1036 {
            get {
                return ResourceManager.GetString("plus1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پذيرنده يا شماره ترمینال پذيرنده صحیح نمیباشد.
        /// </summary>
        internal static string plus1037 {
            get {
                return ResourceManager.GetString("plus1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا: درخواست معتبر, از سمت پذيرنده صورت نگرفته است لطفا اطلاعات پذيرنده خود را چک کنید..
        /// </summary>
        internal static string plus1053 {
            get {
                return ResourceManager.GetString("plus1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار غیرمجاز در ورود اطلاعات.
        /// </summary>
        internal static string plus1055 {
            get {
                return ResourceManager.GetString("plus1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم موقتا قطع میباشد.لطفا بعدا تلاش فرمايید..
        /// </summary>
        internal static string plus1056 {
            get {
                return ResourceManager.GetString("plus1056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرويس پرداخت اينترنتی خارج از سرويس می باشد.لطفا بعدا سعی بفرمايید..
        /// </summary>
        internal static string plus1058 {
            get {
                return ResourceManager.GetString("plus1058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکال در تولید کد يکتا. لطفا مرورگر خود را بسته و با اجرای مجدد مرورگر« عملیات پرداخت را انجام دهید )احتمال استفاده از دکمه Back » مرورگر(.
        /// </summary>
        internal static string plus1061 {
            get {
                return ResourceManager.GetString("plus1061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مجددا سعی بفرمايید.
        /// </summary>
        internal static string plus1064 {
            get {
                return ResourceManager.GetString("plus1064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط ناموفق .لطفا چند لحظه ديگر مجددا سعی کنید.
        /// </summary>
        internal static string plus1065 {
            get {
                return ResourceManager.GetString("plus1065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم سرويس دهی پرداخت موقتا غیر فعال شده است.
        /// </summary>
        internal static string plus1066 {
            get {
                return ResourceManager.GetString("plus1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش به علت بروزرسانی . سیستم موقتا قطع میباشد..
        /// </summary>
        internal static string plus1068 {
            get {
                return ResourceManager.GetString("plus1068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پردازش پارامترهای اختیاری پذيرنده.
        /// </summary>
        internal static string plus1072 {
            get {
                return ResourceManager.GetString("plus1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش نامعتبر است.
        /// </summary>
        internal static string plus1101 {
            get {
                return ResourceManager.GetString("plus1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن ارسالی نامعتبر است.
        /// </summary>
        internal static string plus1103 {
            get {
                return ResourceManager.GetString("plus1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تسهیم صحیح نیست.
        /// </summary>
        internal static string plus1104 {
            get {
                return ResourceManager.GetString("plus1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پذیرنده نزد بانک به تایید نرسیده است..
        /// </summary>
        internal static string plus23 {
            get {
                return ResourceManager.GetString("plus23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پذیرنده نزد بانک به تایید نرسیده است..
        /// </summary>
        internal static string plus3 {
            get {
                return ResourceManager.GetString("plus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام تراکنش مربوطه توسط پايانه ی انجام دهنده مجاز نمی باشد..
        /// </summary>
        internal static string plus58 {
            get {
                return ResourceManager.GetString("plus58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش از حد مجاز بالاتر است.
        /// </summary>
        internal static string plus61 {
            get {
                return ResourceManager.GetString("plus61", resourceCulture);
            }
        }
    }
}
