//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.AsanPardakht {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AsanPardakhtResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsanPardakhtResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlinePayment.AsanPardakht.AsanPardakhtResource", typeof(AsanPardakhtResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ ارسالي محلي پذيرنده نامعتبر است.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ فاكتور براي پيكربندي فعلي پذيرنده معتبر نمي باشد.
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرويس وجود ندارد يا براي پذيرنده فعال نيست.
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هيچ آدرس كال بكي براي درخواست پيكربندي نشده است.
        /// </summary>
        internal static string _109 {
            get {
                return ResourceManager.GetString("_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فاكتور نامعتبر يا تكراري است.
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذيرنده فعال نيست يا پيكربندي پذيرنده غيرمعتبر است.
        /// </summary>
        internal static string _115 {
            get {
                return ResourceManager.GetString("_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای برقراری ارتباط با بانک مقصد.
        /// </summary>
        internal static string _30000 {
            get {
                return ResourceManager.GetString("_30000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید نهایی پرداخت توسط سرور بانک مورد قبول واقع نشد. تراکنش ناموفق بود..
        /// </summary>
        internal static string _30001 {
            get {
                return ResourceManager.GetString("_30001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات تسویه نا موفق بود..
        /// </summary>
        internal static string _30002 {
            get {
                return ResourceManager.GetString("_30002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پيكربندي پذيرنده اينترنتي نامعتبر است.
        /// </summary>
        internal static string plus301 {
            get {
                return ResourceManager.GetString("plus301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كليدهاي رمزنگاري نامعتبر هستند.
        /// </summary>
        internal static string plus302 {
            get {
                return ResourceManager.GetString("plus302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزنگاري نامعتبر است.
        /// </summary>
        internal static string plus303 {
            get {
                return ResourceManager.GetString("plus303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد عناصر درخواست نامعتبر است.
        /// </summary>
        internal static string plus304 {
            get {
                return ResourceManager.GetString("plus304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام كاربري يا رمز عبور پذيرنده نامعتبر است.
        /// </summary>
        internal static string plus305 {
            get {
                return ResourceManager.GetString("plus305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با پرشين سوئيچ تماس بگيريد.
        /// </summary>
        internal static string plus306 {
            get {
                return ResourceManager.GetString("plus306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرور پذيرنده نامعتبر است.
        /// </summary>
        internal static string plus307 {
            get {
                return ResourceManager.GetString("plus307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه فاكتور مي بايست صرفا عدد باشد.
        /// </summary>
        internal static string plus308 {
            get {
                return ResourceManager.GetString("plus308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ فاكتور نادرست ارسال شده است.
        /// </summary>
        internal static string plus309 {
            get {
                return ResourceManager.GetString("plus309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فيلد تاريخ و زمان نامعتبر است.
        /// </summary>
        internal static string plus310 {
            get {
                return ResourceManager.GetString("plus310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت تاريخ و زمان ارسالي پذيرنده نامعتبر است.
        /// </summary>
        internal static string plus311 {
            get {
                return ResourceManager.GetString("plus311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سرويس نامعتبر است.
        /// </summary>
        internal static string plus312 {
            get {
                return ResourceManager.GetString("plus312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پرداخت كننده نامعتبر است.
        /// </summary>
        internal static string plus313 {
            get {
                return ResourceManager.GetString("plus313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید نهایی صورت گرفت. تراکنش با موفقیت انجام شد..
        /// </summary>
        internal static string plus500 {
            get {
                return ResourceManager.GetString("plus500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پردازش هنوز انجام نشده است.
        /// </summary>
        internal static string plus501 {
            get {
                return ResourceManager.GetString("plus501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعيت تراكنش نامشخص است.
        /// </summary>
        internal static string plus502 {
            get {
                return ResourceManager.GetString("plus502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش اصلي ناموفق بوده است.
        /// </summary>
        internal static string plus503 {
            get {
                return ResourceManager.GetString("plus503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا درخواست بازبيني براي اين تراكنش داده شده است.
        /// </summary>
        internal static string plus504 {
            get {
                return ResourceManager.GetString("plus504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا درخواست تسويه براي اين تراكنش ارسال شده است.
        /// </summary>
        internal static string plus505 {
            get {
                return ResourceManager.GetString("plus505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا درخواست بازگشت براي اين تراكنش ارسال شده است.
        /// </summary>
        internal static string plus506 {
            get {
                return ResourceManager.GetString("plus506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش در ليست تسويه قرار دارد.
        /// </summary>
        internal static string plus507 {
            get {
                return ResourceManager.GetString("plus507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش در ليست بازگشت قرار دارد.
        /// </summary>
        internal static string plus508 {
            get {
                return ResourceManager.GetString("plus508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان انجام عمليات به سبب وجود مشكل داخلي وجود ندارد.
        /// </summary>
        internal static string plus509 {
            get {
                return ResourceManager.GetString("plus509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هويت درخواست كننده عمليات نامعتبر است.
        /// </summary>
        internal static string plus510 {
            get {
                return ResourceManager.GetString("plus510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات تایید نهایی و تسویه با موفقیت انجام گردید..
        /// </summary>
        internal static string plus600 {
            get {
                return ResourceManager.GetString("plus600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پردازش هنوز انجام نشده است.
        /// </summary>
        internal static string plus601 {
            get {
                return ResourceManager.GetString("plus601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعيت تراكنش نامشخص است.
        /// </summary>
        internal static string plus602 {
            get {
                return ResourceManager.GetString("plus602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش اصلي ناموفق بوده است.
        /// </summary>
        internal static string plus603 {
            get {
                return ResourceManager.GetString("plus603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش بازبيني نشده است.
        /// </summary>
        internal static string plus604 {
            get {
                return ResourceManager.GetString("plus604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا درخواست بازگشت براي اين تراكنش ارسال شده است.
        /// </summary>
        internal static string plus605 {
            get {
                return ResourceManager.GetString("plus605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا درخواست تسويه براي اين تراكنش ارسال شده است.
        /// </summary>
        internal static string plus606 {
            get {
                return ResourceManager.GetString("plus606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امكان انجام عمليات به سبب وجود مشكل داخلي وجود ندارد.
        /// </summary>
        internal static string plus607 {
            get {
                return ResourceManager.GetString("plus607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش در ليست منتظر بازگشت ها وجود دارد.
        /// </summary>
        internal static string plus608 {
            get {
                return ResourceManager.GetString("plus608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراكنش در ليست منتظر تسويه ها وجود دارد.
        /// </summary>
        internal static string plus609 {
            get {
                return ResourceManager.GetString("plus609", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هويت درخواست كننده عمليات نامعتبر است.
        /// </summary>
        internal static string plus610 {
            get {
                return ResourceManager.GetString("plus610", resourceCulture);
            }
        }
    }
}
