//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.TejarateleParsian {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TejarateleParsianResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TejarateleParsianResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlinePayment.TejarateleParsian.TejarateleParsianResource", typeof(TejarateleParsianResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاي سرور.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده غیرفعال می باشد.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده اهراز هویت نشد.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش با موفقیت برگشت داده شد.
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت خرید براي پذیرنده غیر فعال می باشد.
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت پرداخت قبض براي پذیرنده غیر فعال می باشد..
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت تاپ آپ براي پذیرنده غیر فعال میباشد..
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت شارژ براي پذیرنده غیر فعال می باشد.
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت ارسال تاییده تراکنش براي پذیرنده غیرفعال میباشد..
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت برگشت تراکنش براي پذیرنده غیر فعال میباشد.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش بیش از حد مجاز پذیرنده میباشد..
        /// </summary>
        internal static string _111 {
            get {
                return ResourceManager.GetString("_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفارش تکراري است.
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر ورودي خالی می باشد.
        /// </summary>
        internal static string _113 {
            get {
                return ResourceManager.GetString("_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه قبض نامعتبر می باشد.
        /// </summary>
        internal static string _114 {
            get {
                return ResourceManager.GetString("_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پرداخت نامعتبر می باشد.
        /// </summary>
        internal static string _115 {
            get {
                return ResourceManager.GetString("_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول رشته بیش از حد مجاز می باشد.
        /// </summary>
        internal static string _116 {
            get {
                return ResourceManager.GetString("_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول رشته کم تر از حد مجاز می باشد.
        /// </summary>
        internal static string _117 {
            get {
                return ResourceManager.GetString("_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار ارسال شده عدد نمی باشد.
        /// </summary>
        internal static string _118 {
            get {
                return ResourceManager.GetString("_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان نامعتبر می باشد.
        /// </summary>
        internal static string _119 {
            get {
                return ResourceManager.GetString("_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول داده ورودي معتبر نمی باشد.
        /// </summary>
        internal static string _120 {
            get {
                return ResourceManager.GetString("_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته داده شده بطور کامل عددي نمی باشد.
        /// </summary>
        internal static string _121 {
            get {
                return ResourceManager.GetString("_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شناسایی پذیرنده معتبر نمی باشد.
        /// </summary>
        internal static string _126 {
            get {
                return ResourceManager.GetString("_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس اینترنتی معتبر نمی باشد.
        /// </summary>
        internal static string _127 {
            get {
                return ResourceManager.GetString("_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب آدرس آی پی نامعتبر است..
        /// </summary>
        internal static string _128 {
            get {
                return ResourceManager.GetString("_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان توکن منقضی شده است..
        /// </summary>
        internal static string _130 {
            get {
                return ResourceManager.GetString("_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن نامعتبر.
        /// </summary>
        internal static string _131 {
            get {
                return ResourceManager.GetString("_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش کمتر از حداقل مجاز میباشد.
        /// </summary>
        internal static string _132 {
            get {
                return ResourceManager.GetString("_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید تراکنش توسط پذیرنده انجام شد.
        /// </summary>
        internal static string _1505 {
            get {
                return ResourceManager.GetString("_1505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش برگشت به سوئیچ ارسال شد.
        /// </summary>
        internal static string _1507 {
            get {
                return ResourceManager.GetString("_1507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام عملیات درخواست پرداخت تراکنش ناموفق بود..
        /// </summary>
        internal static string _1527 {
            get {
                return ResourceManager.GetString("_1527", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پرداخت یافت نشد.
        /// </summary>
        internal static string _1528 {
            get {
                return ResourceManager.GetString("_1528", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده مجاز به تایید این تراکنش نمی باشد.
        /// </summary>
        internal static string _1530 {
            get {
                return ResourceManager.GetString("_1530", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید تراکنش ناموفق امکان پذیر نمی باشد.
        /// </summary>
        internal static string _1531 {
            get {
                return ResourceManager.GetString("_1531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش از سوي پذیرنده تایید شد.
        /// </summary>
        internal static string _1532 {
            get {
                return ResourceManager.GetString("_1532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش قبلاً تایید شده است.
        /// </summary>
        internal static string _1533 {
            get {
                return ResourceManager.GetString("_1533", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراخوانی سرویس درخواست شارژ تاپ آپ ناموفق بود..
        /// </summary>
        internal static string _1536 {
            get {
                return ResourceManager.GetString("_1536", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید تراکنش ناموفق می باشد.
        /// </summary>
        internal static string _1540 {
            get {
                return ResourceManager.GetString("_1540", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراخوانی سرویس درخواست پرداخت قبض ناموفق بود.
        /// </summary>
        internal static string _1548 {
            get {
                return ResourceManager.GetString("_1548", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان مجاز براي درخواست برگشت تراکنش به اتمام رسیده است..
        /// </summary>
        internal static string _1549 {
            get {
                return ResourceManager.GetString("_1549", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت تراکنش در وضعیت جاري امکان پذیر نمی باشد.
        /// </summary>
        internal static string _1550 {
            get {
                return ResourceManager.GetString("_1550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت تراکنش قبلا اًنجام شده است.
        /// </summary>
        internal static string _1551 {
            get {
                return ResourceManager.GetString("_1551", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت تراکنش مجاز نمی باشد.
        /// </summary>
        internal static string _1552 {
            get {
                return ResourceManager.GetString("_1552", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاي ناشناخته رخ داده است.
        /// </summary>
        internal static string _32768 {
            get {
                return ResourceManager.GetString("_32768", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات موفق می باشد.
        /// </summary>
        internal static string plus0 {
            get {
                return ResourceManager.GetString("plus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادرکننده ي کارت از انجام تراکنش صرف نظر کرد..
        /// </summary>
        internal static string plus1 {
            get {
                return ResourceManager.GetString("plus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش با مبلغی پایین تر از مبلغ درخواستی )کمبود حساب مشتري ( پذیرفته شده است.
        /// </summary>
        internal static string plus10 {
            get {
                return ResourceManager.GetString("plus10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش نامعتبر است.
        /// </summary>
        internal static string plus12 {
            get {
                return ResourceManager.GetString("plus12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش نادرست است.
        /// </summary>
        internal static string plus13 {
            get {
                return ResourceManager.GetString("plus13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت ارسالی نامعتبر است (وجود ندارد).
        /// </summary>
        internal static string plus14 {
            get {
                return ResourceManager.GetString("plus14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادرکننده ي کارت نامعتبراست (وجود ندارد).
        /// </summary>
        internal static string plus15 {
            get {
                return ResourceManager.GetString("plus15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتري درخواست کننده حذف شده است.
        /// </summary>
        internal static string plus17 {
            get {
                return ResourceManager.GetString("plus17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات تاییدیه این تراکنش قبلا باموفقیت صورت پذیرفته است..
        /// </summary>
        internal static string plus2 {
            get {
                return ResourceManager.GetString("plus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده ي فروشگاهی نامعتبر می باشد.
        /// </summary>
        internal static string plus3 {
            get {
                return ResourceManager.GetString("plus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از انجام تراکنش صرف نظر شد.
        /// </summary>
        internal static string plus5 {
            get {
                return ResourceManager.GetString("plus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز خطایی ناشناخته.
        /// </summary>
        internal static string plus6 {
            get {
                return ResourceManager.GetString("plus6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باتشخیص هویت دارنده ي کارت، تراکنش موفق میباشد..
        /// </summary>
        internal static string plus8 {
            get {
                return ResourceManager.GetString("plus8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تراکنش رد شده است.
        /// </summary>
        internal static string plus80 {
            get {
                return ResourceManager.GetString("plus80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت پذیرفته نشد.
        /// </summary>
        internal static string plus81 {
            get {
                return ResourceManager.GetString("plus81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست رسیده در حال پی گیري و انجام میباشد..
        /// </summary>
        internal static string plus9 {
            get {
                return ResourceManager.GetString("plus9", resourceCulture);
            }
        }
    }
}
