//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePayment.IranKishTokenWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tokenResponse", Namespace="http://schemas.datacontract.org/2004/07/Token")]
    [System.SerializableAttribute()]
    public partial class tokenResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                if ((this.resultField.Equals(value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IranKishTokenWS.ITokens")]
    public interface ITokens {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokens/MakeToken", ReplyAction="http://tempuri.org/ITokens/MakeTokenResponse")]
        OnlinePayment.IranKishTokenWS.tokenResponse MakeToken(string amount, string merchantId, string invoiceNo, string paymentId, string specialPaymentId, string revertURL, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokens/MakeToken", ReplyAction="http://tempuri.org/ITokens/MakeTokenResponse")]
        System.Threading.Tasks.Task<OnlinePayment.IranKishTokenWS.tokenResponse> MakeTokenAsync(string amount, string merchantId, string invoiceNo, string paymentId, string specialPaymentId, string revertURL, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokens/MakeSpecialToken", ReplyAction="http://tempuri.org/ITokens/MakeSpecialTokenResponse")]
        OnlinePayment.IranKishTokenWS.tokenResponse MakeSpecialToken(string amount, string merchantId, string invoiceNo, string paymentId, string specialPaymentId, string revertURL, string description, string extraParam1, string extraParam2, string extraParam3, string extraParam4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokens/MakeSpecialToken", ReplyAction="http://tempuri.org/ITokens/MakeSpecialTokenResponse")]
        System.Threading.Tasks.Task<OnlinePayment.IranKishTokenWS.tokenResponse> MakeSpecialTokenAsync(string amount, string merchantId, string invoiceNo, string paymentId, string specialPaymentId, string revertURL, string description, string extraParam1, string extraParam2, string extraParam3, string extraParam4);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokensChannel : OnlinePayment.IranKishTokenWS.ITokens, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokensClient : System.ServiceModel.ClientBase<OnlinePayment.IranKishTokenWS.ITokens>, OnlinePayment.IranKishTokenWS.ITokens {
        
        public TokensClient() {
        }
        
        public TokensClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokensClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokensClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokensClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlinePayment.IranKishTokenWS.tokenResponse MakeToken(string amount, string merchantId, string invoiceNo, string paymentId, string specialPaymentId, string revertURL, string description) {
            return base.Channel.MakeToken(amount, merchantId, invoiceNo, paymentId, specialPaymentId, revertURL, description);
        }
        
        public System.Threading.Tasks.Task<OnlinePayment.IranKishTokenWS.tokenResponse> MakeTokenAsync(string amount, string merchantId, string invoiceNo, string paymentId, string specialPaymentId, string revertURL, string description) {
            return base.Channel.MakeTokenAsync(amount, merchantId, invoiceNo, paymentId, specialPaymentId, revertURL, description);
        }
        
        public OnlinePayment.IranKishTokenWS.tokenResponse MakeSpecialToken(string amount, string merchantId, string invoiceNo, string paymentId, string specialPaymentId, string revertURL, string description, string extraParam1, string extraParam2, string extraParam3, string extraParam4) {
            return base.Channel.MakeSpecialToken(amount, merchantId, invoiceNo, paymentId, specialPaymentId, revertURL, description, extraParam1, extraParam2, extraParam3, extraParam4);
        }
        
        public System.Threading.Tasks.Task<OnlinePayment.IranKishTokenWS.tokenResponse> MakeSpecialTokenAsync(string amount, string merchantId, string invoiceNo, string paymentId, string specialPaymentId, string revertURL, string description, string extraParam1, string extraParam2, string extraParam3, string extraParam4) {
            return base.Channel.MakeSpecialTokenAsync(amount, merchantId, invoiceNo, paymentId, specialPaymentId, revertURL, description, extraParam1, extraParam2, extraParam3, extraParam4);
        }
    }
}
